#!/usr/bin/env python3
"""Regenerate requirements-lock.txt from pyproject.toml.

Resolves the core runtime dependencies plus the `web` and `dev` extras --
deliberately not `nli-local`, see the note at the bottom of the generated
file -- for the exact platform and interpreter CI's "Build and verify a
clean install" job uses (ubuntu-latest, Python 3.12), using pip's own
dependency resolver so the lock is never hand-edited and never drifts
from what `pyproject.toml` actually declares.

Usage:
    python scripts/generate-lock.py

Requires network access to resolve against PyPI. Commit the result.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = ROOT / "requirements-lock.txt"

# Matches the "Build and verify a clean install" CI job exactly --
# ubuntu-latest, Python 3.12 -- which is the install this lock exists to
# make verifiable.
TARGET_PYTHON = "3.12"
TARGET_PLATFORM = "manylinux2014_x86_64"
TARGET_ABI = "cp312"
TARGET_IMPLEMENTATION = "cp"

HEADER = """\
# Generated by scripts/generate-lock.py. Do not hand-edit.
#
# Hash-pinned resolution of the core runtime dependencies plus the `web`
# and `dev` extras, for {platform} / Python {python} ({abi}) -- the exact
# target CI's "Build and verify a clean install" job runs on. Install
# with:
#
#     pip install --require-hashes -r requirements-lock.txt
#
# Deliberately excludes `nli-local` (torch, transformers, safetensors,
# sentencepiece). Torch ships different wheels per platform and CUDA
# build, and centrally pinning one by hash would be wrong for most users
# who install it -- see pyproject.toml's own comment on why nli-local is
# optional in the first place. Install it separately and unpinned via
# `pip install -e ".[nli-local]"`; the version range in pyproject.toml is
# the only guarantee given for it.
#
# This is hash-pinned dependency integrity, not a hermetic build or a
# supply-chain attestation: it proves the exact bytes installed match
# what was resolved here, not that the resolution itself is reproducible
# on every platform, or that nothing upstream could still be compromised
# before this file is next regenerated.
"""


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        report_path = Path(tmp) / "report.json"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--dry-run",
                "--ignore-installed",
                "--python-version",
                TARGET_PYTHON,
                "--platform",
                TARGET_PLATFORM,
                "--abi",
                TARGET_ABI,
                "--implementation",
                TARGET_IMPLEMENTATION,
                "--only-binary=:all:",
                "--report",
                str(report_path),
                f"{ROOT}[web,dev]",
            ],
            check=True,
            cwd=ROOT,
        )
        report = json.loads(report_path.read_text())

    lines = [HEADER.format(platform=TARGET_PLATFORM, python=TARGET_PYTHON, abi=TARGET_ABI), ""]
    entries = []
    for item in report["install"]:
        meta = item["metadata"]
        name = meta["name"]
        if name == "agentic-research-engine":
            continue  # the project itself; installed separately with -e
        version = meta["version"]
        download = item.get("download_info", {})
        archive = download.get("archive_info", {})
        hashes = archive.get("hashes", {})
        sha256 = hashes.get("sha256")
        if sha256 is None:
            raise SystemExit(f"no sha256 hash available for {name}=={version}; cannot lock it")
        entries.append((name, version, sha256))

    for name, version, sha256 in sorted(entries):
        lines.append(f"{name}=={version} \\\n    --hash=sha256:{sha256}")

    LOCK_PATH.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(entries)} pinned packages to {LOCK_PATH}")


if __name__ == "__main__":
    main()
