"""Markdown rendering of a finished run.

Kept separate from synthesis so that presentation can change without touching
the reasoning pipeline, and so a stored run can be re-rendered from its JSON
artifacts without re-running any model.
"""

from __future__ import annotations

from datetime import UTC, datetime

from agentic_research.metrics import RunMetrics
from agentic_research.models import (
    CitationVerification,
    Claim,
    ResearchReport,
    SourceDocument,
)


def render_markdown(
    report: ResearchReport,
    sources: list[SourceDocument],
    verification: CitationVerification | None,
    metrics: RunMetrics | None = None,
) -> str:
    """Render the report, its sources, and an honest verification footer."""
    cited = report.cited_ids()
    lines: list[str] = [f"# {report.title}", ""]

    if report.executive_summary:
        lines += ["## Summary", "", report.executive_summary.strip(), ""]

    if report.key_findings:
        lines += ["## Key findings", ""]
        for claim in report.key_findings:
            lines.append(f"- {_claim_text(claim)}")
        lines.append("")

    for section in report.sections:
        lines += [f"## {section.heading}", ""]
        for claim in section.claims:
            lines.append(_claim_text(claim))
            lines.append("")

    if report.contradictions:
        lines += [
            "## Where sources disagree",
            "",
            "_Preserved rather than resolved; the underlying sources genuinely differ._",
            "",
        ]
        lines += [f"- {item}" for item in report.contradictions]
        lines.append("")

    if report.limitations:
        lines += ["## Limitations", ""]
        lines += [f"- {item}" for item in report.limitations]
        lines.append("")

    usable = [s for s in sources if s.is_usable and not s.duplicate_of]
    if usable:
        lines += ["## Sources", ""]
        for source in sorted(usable, key=_source_order):
            date = source.published_date.date().isoformat() if source.published_date else "n.d."
            used = "" if source.id in cited else " _(retrieved, not cited)_"
            lines.append(
                f"- **[{source.id}]** [{source.title}]({source.url}) — "
                f"{source.domain}, {source.source_type.value}, {date}, "
                f"quality {source.quality_score:.2f}{used}"
            )
        lines.append("")

    if verification is not None:
        lines += _verification_section(verification)

    if metrics is not None:
        lines += _metrics_section(metrics)

    lines += [
        "---",
        "",
        f"_Generated by Agentic Research Engine on "
        f"{datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}._",
    ]
    return "\n".join(lines).rstrip() + "\n"


def _claim_text(claim: Claim) -> str:
    """Render a claim with its citation markers appended.

    Markers are generated here from ``citation_ids`` rather than taken from
    the model's prose, so what the reader sees is exactly what verification
    checked.
    """
    text = claim.text.strip()
    markers = "".join(f"[{cid}]" for cid in claim.citation_ids)
    if markers:
        text = f"{text.rstrip('.')}. {markers}" if not text.endswith(markers) else text
    if claim.is_interpretation:
        text = f"{text} *(interpretation)*"
    return text


def _source_order(source: SourceDocument) -> tuple[int, str]:
    digits = "".join(ch for ch in source.id if ch.isdigit())
    return (int(digits) if digits else 0, source.id)


def _verification_section(verification: CitationVerification) -> list[str]:
    lines = ["## Citation verification", ""]
    lines.append(
        f"- Citations: {verification.total_citations}, "
        f"{verification.valid_citations} resolve to a retrieved source "
        f"({verification.citation_validity_rate:.0%})"
    )
    lines.append(
        f"- Factual claims carrying a citation: "
        f"{verification.citation_coverage_rate:.0%} of {verification.factual_claims}"
    )
    if verification.checked_claims:
        lines.append(
            f"- Entailment-checked claims: {verification.supported_claims}"
            f"/{verification.checked_claims} judged supported by their cited evidence "
            f"({verification.support_rate:.0%})"
        )
    if verification.repaired:
        lines.append(
            "- Citations pointing at sources that were never retrieved were removed "
            "automatically; the affected sentences now appear without a citation."
        )
    if verification.unused_source_ids:
        lines.append(f"- Retrieved but never cited: {', '.join(verification.unused_source_ids)}")
    problems = [i for i in verification.issues if i.severity in ("error", "warning")]
    if problems:
        lines += ["", "<details><summary>Open citation issues</summary>", ""]
        for issue in problems[:20]:
            lines.append(f"- `{issue.type.value}` {issue.detail} — {issue.claim_text[:120]}")
        lines += ["", "</details>"]
    lines.append("")
    return lines


def _metrics_section(metrics: RunMetrics) -> list[str]:
    lines = ["## Run metrics", "", "| Metric | Value |", "| --- | --- |"]
    rows = [
        ("Mode", metrics.mode),
        ("Research rounds", metrics.research_rounds),
        ("Stopped because", metrics.stop_reason or "coverage sufficient"),
        ("Search queries", metrics.search_queries),
        ("Unique sources", metrics.unique_sources),
        ("Usable sources", metrics.usable_sources),
        ("Distinct domains", metrics.distinct_domains),
        ("Fetches avoided by dedup", metrics.fetches_avoided),
        ("Evidence items", metrics.evidence_items),
        ("Quote verification rate", f"{metrics.quote_verification_rate:.0%}"),
        ("LLM calls", metrics.llm_calls),
        ("Tokens (in/out)", f"{metrics.input_tokens:,} / {metrics.output_tokens:,}"),
        ("Estimated cost", metrics.cost_display),
        ("Duration", f"{metrics.duration_s:.1f}s"),
    ]
    lines += [f"| {label} | {value} |" for label, value in rows]
    lines.append("")
    return lines
