"""Markdown rendering of a finished run.

Kept separate from synthesis so that presentation can change without touching
the reasoning pipeline, and so a stored run can be re-rendered from its JSON
artifacts without re-running any model.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime

from agentic_research.evidence.store import EvidenceStore
from agentic_research.metrics import RunMetrics
from agentic_research.models import (
    CitationVerification,
    Claim,
    ClaimKind,
    EvidenceItem,
    ResearchReport,
    SourceDocument,
)


def render_markdown(
    report: ResearchReport,
    sources: list[SourceDocument],
    verification: CitationVerification | None,
    metrics: RunMetrics | None = None,
    evidence: Sequence[EvidenceItem] | None = None,
) -> str:
    """Render the report, its sources, and an honest verification footer."""
    store = EvidenceStore(sources, list(evidence or []))
    cited = report.cited_ids()
    lines: list[str] = [f"# {report.title}", ""]
    # The question in full, once, under the title. A title is a label and
    # gets shortened; the question is the thing the report answers and
    # must never be delivered half-finished.
    if metrics is not None and metrics.query:
        lines += [f"**Question:** {metrics.query}", ""]

    if report.summary_claims:
        lines += ["## Summary", ""]
        # Rendered as prose, but each sentence is a verified Claim carrying
        # its own evidence, not an unchecked blob.
        lines.append(" ".join(_claim_text(c, store) for c in report.summary_claims))
        lines.append("")

    if report.key_findings:
        lines += ["## Key findings", ""]
        for claim in report.key_findings:
            lines.append(f"- {_claim_text(claim, store)}")
        lines.append("")

    for section in report.sections:
        lines += [f"## {section.heading}", ""]
        for claim in section.claims:
            lines.append(_claim_text(claim, store))
            lines.append("")

    if report.contradictions:
        lines += [
            "## Where sources disagree",
            "",
            "_Preserved rather than resolved; the underlying sources genuinely differ._",
            "",
        ]
        for contradiction in report.contradictions:
            left = _markers(contradiction.left_citation_ids)
            right = _markers(contradiction.right_citation_ids)
            flag = "" if contradiction.is_auditable else " _(one side unevidenced)_"
            lines.append(
                f"- **{contradiction.topic}** — {contradiction.left_summary.rstrip('.')}"
                f" {left}, while {contradiction.right_summary.rstrip('.')} {right}.{flag}"
            )
        lines.append("")

    if report.limitations:
        lines += ["## Limitations", ""]
        lines += [f"- {item}" for item in report.limitations]
        lines.append("")

    usable = [s for s in sources if s.is_usable and not s.duplicate_of]
    if usable:
        lines += ["## Sources", ""]
        for source in sorted(usable, key=_source_order):
            date = source.published_date.date().isoformat() if source.published_date else "n.d."
            used = "" if source.id in cited else " _(retrieved, not cited)_"
            lines.append(
                f"- **[{source.id}]** [{source.title}]({source.url}) — "
                f"{source.domain}, {source.source_type.value}, {date}, "
                f"quality {source.quality_score:.2f}{used}"
            )
        lines.append("")

    if verification is not None:
        lines += _verification_section(verification)

    if metrics is not None:
        lines += _metrics_section(metrics)

    lines += [
        "---",
        "",
        f"_Generated by Agentic Research Engine on "
        f"{datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}._",
    ]
    return "\n".join(lines).rstrip() + "\n"


def _markers(citation_ids: list[str], pages: dict[str, int] | None = None) -> str:
    """Render citation markers, with page numbers where genuinely known."""
    pages = pages or {}
    parts = []
    for cid in citation_ids:
        page = pages.get(cid)
        parts.append(f"[{cid}, p. {page}]" if page else f"[{cid}]")
    return "".join(parts)


def _claim_text(claim: Claim, store: EvidenceStore | None = None) -> str:
    """Render a claim with markers derived from its resolved citations.

    Markers are generated from ``citation_ids``, which the engine derived from
    ``evidence_ids``. Nothing bracket-shaped that a model typed into the prose
    survives to this point, so every marker a reader sees was verified.
    """
    text = claim.text.strip()
    pages: dict[str, int] = {}
    if store is not None:
        for evidence_id in claim.evidence_ids:
            item = store.evidence_by_id(evidence_id)
            if item is not None and item.page:
                pages.setdefault(item.source_id, item.page)
    markers = _markers(claim.citation_ids, pages)
    if markers:
        text = f"{text.rstrip('.')}. {markers}"
    if claim.kind is ClaimKind.SYNTHESIS:
        text = f"{text} *(synthesis)*"
    return text


def _source_order(source: SourceDocument) -> tuple[int, str]:
    digits = "".join(ch for ch in source.id if ch.isdigit())
    return (int(digits) if digits else 0, source.id)


def _verification_section(verification: CitationVerification) -> list[str]:
    lines = ["## Citation verification", ""]
    lines.append(
        f"- Evidence references: {verification.total_evidence_refs}, "
        f"{verification.resolvable_evidence_refs} resolved to citable evidence "
        f"({verification.evidence_integrity_rate:.0%}). "
        "Citation markers are derived from those references by the engine, so "
        "citation integrity is a structural invariant rather than a measurement."
    )
    lines.append(
        f"- Evidence-owing claims carrying a citation: "
        f"{verification.citation_coverage_rate:.0%} of {verification.substantive_claims}"
    )
    if verification.checked_claims:
        breakdown = verification.support_breakdown
        scope = (
            "every eligible claim"
            if verification.entailment_exhaustive
            else (
                f"a sample of {verification.checked_claims} of "
                f"{verification.checkable_claims} eligible claims"
            )
        )
        lines.append(
            f"- Entailment checked against each claim's own evidence, over {scope}: "
            f"{breakdown['supported']} supported, "
            f"{breakdown['partially_supported']} partially supported, "
            f"{breakdown['unsupported']} unsupported, "
            f"{breakdown['not_checked']} not checked"
        )
    if verification.contradictions_total:
        lines.append(
            f"- Contradictions: {verification.contradictions_auditable} of "
            f"{verification.contradictions_total} have citable evidence on both sides"
        )
    if verification.repaired:
        lines.append(
            "- References to nonexistent or unverifiable evidence were removed "
            "automatically; the affected sentences now appear without a citation."
        )
    if verification.unused_source_ids:
        lines.append(f"- Retrieved but never cited: {', '.join(verification.unused_source_ids)}")
    problems = [i for i in verification.issues if i.severity in ("error", "warning")]
    if problems:
        lines += ["", "<details><summary>Open citation issues</summary>", ""]
        for issue in problems[:20]:
            lines.append(f"- `{issue.type.value}` {issue.detail} — {issue.claim_text[:120]}")
        lines += ["", "</details>"]
    lines.append("")
    return lines


def _metrics_section(metrics: RunMetrics) -> list[str]:
    lines = ["## Run metrics", "", "| Metric | Value |", "| --- | --- |"]
    rows = [
        ("Mode", metrics.mode),
        ("Research rounds", metrics.research_rounds),
        ("Stopped because", metrics.stop_reason or "coverage sufficient"),
        ("Search queries", metrics.search_queries),
        ("Unique sources", metrics.unique_sources),
        ("Usable sources", metrics.usable_sources),
        ("Distinct domains", metrics.distinct_domains),
        ("Fetches avoided by dedup", metrics.fetches_avoided),
        ("Evidence items", metrics.evidence_items),
        ("Quotes verbatim (exact-normalised)", f"{metrics.quote_fidelity_rate:.0%}"),
        ("Quotes fuzzy (excluded from citation)", f"{metrics.fuzzy_quote_rate:.0%}"),
        ("LLM calls", metrics.llm_calls),
        ("Tokens (in/out)", f"{metrics.input_tokens:,} / {metrics.output_tokens:,}"),
        ("Estimated cost", metrics.cost_display),
        ("Duration", f"{metrics.duration_s:.1f}s"),
    ]
    lines += [f"| {label} | {value} |" for label, value in rows]
    lines.append("")
    return lines
