"""Guards in the Phase B review tooling: the blinding leak scanner, the
reviewer score sheet's strict validation, and the paired-vs-unpaired
quality-comparison split.

These scripts live under `scripts/`, not `src/`, because they are a
one-off benchmark's tooling rather than library code the engine
depends on -- but the guards in them are exactly the kind of thing a
silent regression would be expensive to discover late (a validation
gap here would let an incomplete or corrupted human review pass as
real data), so they get the same directed-unit-test treatment as any
other correctness-critical check in this repository.
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))

from join_phase_b_review import (  # noqa: E402
    SCORE_COLUMNS,
    ReviewValidationError,
    validate_and_load,
)
from prepare_phase_b_review import BlindingLeakError, scan_for_leaks  # noqa: E402
from reconcile_phase_b_review import paired_and_unpaired  # noqa: E402

VALID_ROW = {
    "random_id": "abc123",
    "question_id": "Q1-definition",
    "relevance_1to5": "4",
    "completeness_1to5": "3",
    "clarity_1to5": "5",
    "claim_support_1to5": "2",
    "citation_usefulness_1to5": "3",
    "harmful_or_unsupported_claims_yn": "No",
    "harmful_or_unsupported_claims_note": "",
    "rationale": "Clear and on-topic.",
}
VALID_KEY = {
    "reviewable": {"abc123": {"question_id": "Q1-definition", "repetition": 1, "arm": "local"}},
    "unreviewable_timeouts": [],
}


def _write_reviewer_dir(tmp_path: Path, rows: list[dict[str, str]], key: dict) -> Path:
    reviewer_dir = tmp_path / "reviewer_x"
    reviewer_dir.mkdir()
    with (reviewer_dir / "scores_template.csv").open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    (reviewer_dir / "unblinding_key.json").write_text(json.dumps(key))
    return reviewer_dir


class TestScanForLeaks:
    def test_passes_clean_text(self) -> None:
        scan_for_leaks("This is a clean research report with no identifiers.", context="test")

    def test_catches_a_known_provider_identifier(self) -> None:
        with pytest.raises(BlindingLeakError):
            scan_for_leaks("Retrieved via the openai API.", context="test")

    def test_catches_a_known_model_identifier(self) -> None:
        with pytest.raises(BlindingLeakError):
            scan_for_leaks("Generated by qwen3:4b locally.", context="test")

    def test_catches_the_bracketed_arm_leak_this_scanner_was_built_for(self) -> None:
        """The actual historical bug: `blind(arm.upper(), ...)` produced
        literal `[LOCAL]`/`[CLOUD]` markers in blinded output."""
        with pytest.raises(BlindingLeakError):
            scan_for_leaks("community.[CLOUD].com", context="test")
        with pytest.raises(BlindingLeakError):
            scan_for_leaks("Served by [LOCAL] model.", context="test")

    def test_catches_the_redaction_count_side_channel(self) -> None:
        with pytest.raises(BlindingLeakError):
            scan_for_leaks("<!-- redactions: 3 -->\n\nSome text.", context="test")


class TestStrictScoreValidation:
    def test_a_fully_valid_sheet_passes(self, tmp_path: Path) -> None:
        reviewer_dir = _write_reviewer_dir(tmp_path, [VALID_ROW], VALID_KEY)
        rows, key = validate_and_load(reviewer_dir)
        assert len(rows) == 1
        assert key == VALID_KEY

    @pytest.mark.parametrize("column", SCORE_COLUMNS)
    def test_rejects_a_blank_score(self, tmp_path: Path, column: str) -> None:
        row = {**VALID_ROW, column: ""}
        reviewer_dir = _write_reviewer_dir(tmp_path, [row], VALID_KEY)
        with pytest.raises(ReviewValidationError, match=f"{column} is blank"):
            validate_and_load(reviewer_dir)

    def test_rejects_a_non_integer_score(self, tmp_path: Path) -> None:
        row = {**VALID_ROW, "relevance_1to5": "four"}
        reviewer_dir = _write_reviewer_dir(tmp_path, [row], VALID_KEY)
        with pytest.raises(ReviewValidationError, match="not an integer"):
            validate_and_load(reviewer_dir)

    @pytest.mark.parametrize("value", ["0", "6", "-1", "10"])
    def test_rejects_a_score_outside_1_to_5(self, tmp_path: Path, value: str) -> None:
        row = {**VALID_ROW, "relevance_1to5": value}
        reviewer_dir = _write_reviewer_dir(tmp_path, [row], VALID_KEY)
        with pytest.raises(ReviewValidationError, match="outside 1-5"):
            validate_and_load(reviewer_dir)

    @pytest.mark.parametrize("value", ["", "maybe", "y", "true", "1"])
    def test_rejects_an_invalid_yes_no_flag(self, tmp_path: Path, value: str) -> None:
        row = {**VALID_ROW, "harmful_or_unsupported_claims_yn": value}
        reviewer_dir = _write_reviewer_dir(tmp_path, [row], VALID_KEY)
        with pytest.raises(ReviewValidationError, match="must be exactly Yes or No"):
            validate_and_load(reviewer_dir)

    def test_rejects_an_empty_rationale(self, tmp_path: Path) -> None:
        row = {**VALID_ROW, "rationale": "   "}
        reviewer_dir = _write_reviewer_dir(tmp_path, [row], VALID_KEY)
        with pytest.raises(ReviewValidationError, match="rationale is empty"):
            validate_and_load(reviewer_dir)

    def test_rejects_a_duplicate_random_id(self, tmp_path: Path) -> None:
        key = {
            "reviewable": {
                "abc123": {"question_id": "Q1-definition", "repetition": 1, "arm": "local"},
                "def456": {"question_id": "Q1-definition", "repetition": 2, "arm": "local"},
            },
            "unreviewable_timeouts": [],
        }
        rows = [VALID_ROW, {**VALID_ROW, "random_id": "abc123"}]  # same ID twice
        reviewer_dir = _write_reviewer_dir(tmp_path, rows, key)
        with pytest.raises(ReviewValidationError, match="duplicate random_id"):
            validate_and_load(reviewer_dir)

    def test_rejects_a_missing_id_not_in_the_score_sheet(self, tmp_path: Path) -> None:
        key = {
            "reviewable": {
                "abc123": {"question_id": "Q1-definition", "repetition": 1, "arm": "local"},
                "zzz999": {"question_id": "Q2-numeric-lookup", "repetition": 1, "arm": "cloud"},
            },
            "unreviewable_timeouts": [],
        }
        reviewer_dir = _write_reviewer_dir(tmp_path, [VALID_ROW], key)  # only scores abc123
        with pytest.raises(ReviewValidationError, match="missing from the score sheet"):
            validate_and_load(reviewer_dir)

    def test_rejects_an_id_in_the_sheet_that_is_not_in_the_key(self, tmp_path: Path) -> None:
        extra_row = {**VALID_ROW, "random_id": "notinkey"}
        reviewer_dir = _write_reviewer_dir(tmp_path, [VALID_ROW, extra_row], VALID_KEY)
        with pytest.raises(ReviewValidationError, match="not present in unblinding_key"):
            validate_and_load(reviewer_dir)

    def test_rejects_a_question_id_that_does_not_match_the_key(self, tmp_path: Path) -> None:
        """Catches a reviewer pasting a score into the wrong row: the
        random ID is real, but the question_id column was typed/copied
        in for a different question than the key actually maps it to.
        """
        row = {**VALID_ROW, "question_id": "Q2-numeric-lookup"}
        reviewer_dir = _write_reviewer_dir(tmp_path, [row], VALID_KEY)
        with pytest.raises(ReviewValidationError, match="does not match"):
            validate_and_load(reviewer_dir)


class TestJoinAgainstRealData:
    """One integration test against the actual committed raw_results.json,
    proving the full pipeline wiring (not just the isolated validator)
    works against real recorded runs -- a known-ok run and a known-
    timeout run."""

    def test_a_real_scored_run_and_a_real_timeout_join_correctly(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        import join_phase_b_review as m

        monkeypatch.setattr(m, "REVIEW", tmp_path)
        key = {
            "reviewable": {
                "abc123": {"question_id": "Q1-definition", "repetition": 1, "arm": "local"}
            },
            "unreviewable_timeouts": [
                {
                    "question_id": "Q4-comparison",
                    "repetition": 1,
                    "arm": "local",
                    "reason": "arm did not complete within 120s",
                }
            ],
        }
        _write_reviewer_dir(tmp_path, [VALID_ROW], key)
        (tmp_path / "reviewer_x").rename(tmp_path / "reviewer_a")

        joined = m.join("a")
        assert len(joined) == 2
        scored = next(r for r in joined if r["status"] == "SCORED")
        timeout = next(r for r in joined if r["status"] == "TIMEOUT_NO_OUTPUT")
        assert scored["question_id"] == "Q1-definition"
        assert scored["known_cost_usd"] == 0.0  # local arm, real recorded value
        assert timeout["timed_out"] is True
        assert timeout["known_cost_usd"] == 0.0


class TestPairedAndUnpaired:
    def test_both_arms_scored_is_paired(self) -> None:
        rows = [
            {"question_id": "Q1", "repetition": 1, "arm": "local", "status": "SCORED"},
            {"question_id": "Q1", "repetition": 1, "arm": "cloud", "status": "SCORED"},
        ]
        paired, unpaired = paired_and_unpaired(rows)
        assert paired == {("Q1", 1)}
        assert unpaired == set()

    def test_one_arm_timed_out_is_unpaired(self) -> None:
        rows = [
            {"question_id": "Q4", "repetition": 1, "arm": "local", "status": "TIMEOUT_NO_OUTPUT"},
            {"question_id": "Q4", "repetition": 1, "arm": "cloud", "status": "SCORED"},
        ]
        paired, unpaired = paired_and_unpaired(rows)
        assert paired == set()
        assert unpaired == {("Q4", 1)}

    def test_a_cloud_only_run_never_silently_joins_the_paired_set(self) -> None:
        """The actual bug class this guards against: averaging 19 paired
        local outputs against all 24 cloud outputs compares different
        populations. This asserts the 5 known unpaired reps from the
        real Phase B data are excluded from `paired`."""
        rows = []
        for qid, rep in [
            ("Q4-comparison", 1),
            ("Q5-relationship", 1),
            ("Q5-relationship", 2),
            ("Q6-causal", 2),
            ("Q9-ambiguous", 1),
        ]:
            rows.append(
                {
                    "question_id": qid,
                    "repetition": rep,
                    "arm": "local",
                    "status": "TIMEOUT_NO_OUTPUT",
                }
            )
            rows.append({"question_id": qid, "repetition": rep, "arm": "cloud", "status": "SCORED"})
        paired, unpaired = paired_and_unpaired(rows)
        assert paired == set()
        assert len(unpaired) == 5
